sudo: false
language: node_js
node_js:
  - "5.3"
addons:
  firefox: "46.0"
cache:
  directories:
    - node_modules
install:
  - travis_retry npm install
  - npm install -g coveralls@2.11.3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - gulp lint:js
  - gulp lint:html
  - wct --local=firefox # coverage
  - travis_retry gulp test:mobile
  - travis_retry gulp test:desktop
  - travis_retry gulp test:mobile:shadow
  - travis_retry gulp test:desktop:shadow
after_success: "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
