sudo: false
dist: trusty
language: node_js
node_js: stable

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

before_script:
  - gulp lint
  - xvfb-run sh run-lighthouse-tests.sh
  - SKIP_SAUCELABS=true xvfb-run -s '-screen 0 1024x768x24' wct -l chrome -l firefox

script:
  - ([[ $TRAVIS_EVENT_TYPE = pull_request || $TRAVIS_BRANCH = quick/* ]] || xvfb-run -s '-screen 0 1024x768x24' wct)
